### ISSUE TITLE
How to figure out the current playing item?

### ISSUE THREAD

**Issue by solarhell** [Blocklevel/vue-howler#8]
Thanks for your lib!
I'm not familiar with Vue's mixins.
In my case, i have an array like
```javascript
audioSources: [
  {
    src: 'a.flac',
    pic: 'a.jpg'
  },
  {
    src: 'b.flac',
    pic: 'b.jpg'
  },
  {
    src: 'c.flac',
    pic: 'c.jpg'
  }
]
```

I already modified the init method so i can play the music.
But i want to know how to get current playing item or id so that i can get the following pic for the music.

**Comment by mickdekkers** [comment]
Hello, good question!

The `audioSources` array is only meant to contain the audio sources for a single piece of sound or music.
It's an array so that, if the browser is not compatible with the first item, it will try to load the second, and so on.
For more details, see the `src` option in the [Howler.js docs](https://github.com/goldfire/howler.js#src-array--required).

If you want to change the song that is being played, you can update the `audioSources` array with the sources for the new song and call the `play` method again.

Let me know if that helps :)

**Comment by mickdekkers** [comment]
You may also want to upgrade vue-howler to 0.3.3, because I fixed [a bug](https://github.com/Blocklevel/vue-howler/issues/9) that might have affected you otherwise.

**Comment by solarhell** [comment]
Thanks! This makes sense.

**Comment by tetreault** [comment]
I'm having an odd case. I have a computed property for `audioSources`. on the first click of a track it says the audio source is undefined, any subsequent clicks work as expected though. 

```
  audioSources() {
      if (this.$store.state.isTrack1Playing) {
        return ['/audio/placeholder.mp3'];
      } else if (this.$store.state.isTrack2Playing) {
        return ['/audio/placeholder-2.mp3'];
      } else if (this.$store.state.isTrack3Playing) {
        return ['/audio/placeholder.mp3'];
      } else if (this.$store.state.isTrack4Playing) {
        return ['/audio/placeholder-2.mp3'];
      } else if (this.$store.state.isTrack5Playing) {
        return ['/audio/placeholder.mp3'];
      } else if (this.$store.state.isTrack6Playing) {
        return ['/audio/placeholder-2.mp3'];
      } else if (this.$store.state.isTrack7Playing) {
        return ['/audio/placeholder.mp3'];
      } else {
        return ['/audio/placeholder-2.mp3'];
      }
    }
```

Is there something subtle i'm missing here? I expect the last `else` to be returned on page load since none of the tracks in the store have playing state of true.

**Comment by tetreault** [comment]
to expand on this, I can confirm when I console log out `this.audioSources` I see the expected value. But in the vue-events dashboard in the chrome inspector I see the payload[0] is undefined?

<img width="251" alt="screenshot 2018-07-26 09 13 44" src="https://user-images.githubusercontent.com/5934354/43264489-59de8946-90b4-11e8-925b-4f8ef534d437.png">

**Comment by tetreault** [comment]
further info: 

- this issue only occurs in chrome & ff but not in safari
